---
#Ansible Playbook to build and run a Docker container
 
- name: Playbook to Configure Slave Node
  hosts: all
  become: true
  gather_facts: true

  tasks:    
    - name: install python pip
      apt:
        name: python-pip
        state: present

    - name: install docker
      apt:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
